<script setup>
import { computed, nextTick, onBeforeUnmount, onMounted, ref } from 'vue'
import { ArrowUpRight, Check, ChevronRight, ClipboardCheck, Crosshair, Download, Flame, Lightbulb, Plus, Search, ShieldCheck, Users, Video, Wind, X, Zap } from 'lucide-vue-next'
import { useTwin } from '../composables/useTwin.js'
import { buildings, devices, cameras, facilities, getRoom, getBuilding, energySeries, telemetry, rooms, deviceReading, weatherForecast } from '../data/campus.js'
import TrendChart from './TrendChart.vue'
const {state,tick,modal,room,building,selectedAlertId,locateAlert,advanceAlert,addVisitor,toggleVisitor,selectRoom,controlRoom,notify,persist}=useTwin()
const dialog=ref(null),search=ref(''),system=ref('全部'),note=ref(''),assignee=ref('张工'),energyKind=ref('electricity'),cameraId=ref(building.value?.id||'A')
const visitor=ref({name:'',company:'',buildingId:'A'})
const tab=ref('active')
let priorFocus
const titles={alerts:'告警与工单中心',assets:'设备台账与空间档案',visitors:'访客管理与电子围栏',video:'视频巡检',energy:'能源分析与运行优化',help:'使用指南与系统说明'}
const alerts=computed(()=>state.alerts.filter(a=>tab.value==='all'||(tab.value==='active'?a.status!=='closed':a.status==='closed')))
const selected=computed(()=>alerts.value.find(a=>a.id===selectedAlertId.value)||alerts.value[0])
const assetList=computed(()=>[...devices,...cameras,...facilities].filter(d=>(!room.value||d.roomId===room.value.id)&&(system.value==='全部'||d.system===system.value)&&(`${d.id}${d.label}${d.roomId||''}`.toLowerCase().includes(search.value.toLowerCase()))))
const assetPage=ref(1),pageSize=15
const pageAssets=computed(()=>assetList.value.slice((Math.min(assetPage.value,Math.max(1,Math.ceil(assetList.value.length/pageSize)))-1)*pageSize,Math.min(assetPage.value,Math.max(1,Math.ceil(assetList.value.length/pageSize)))*pageSize))
const statuses={new:'待诊断',diagnosed:'待派单',assigned:'处理中',resolved:'待复核',closed:'已闭环'}
const actions={diagnose:'完成诊断',assign:'派发工单',resolve:'提交处理结果',close:'复核并闭环'}
const nextAction={new:'diagnose',diagnosed:'assign',assigned:'resolve',resolved:'close'}
const series=computed(()=>energySeries(state.buildingId,energyKind.value,{floor:state.floor,roomId:state.roomId}))
const energyTotal=computed(()=>series.value.reduce((sum,d)=>sum+d.value,0))
const rank=computed(()=>buildings.map(b=>({ ...b,power:rooms.filter(r=>r.buildingId===b.id).reduce((n,r)=>n+telemetry(r,tick.value,state.controls[r.id]).power,0)})).sort((a,b)=>b.power-a.power))
const efficiencyApplied=ref(false)
function process(){const a=selected.value;if(!a)return;const action=nextAction[a.status];if(action==='resolve'&&!note.value.trim()){notify('请填写现场处理记录后再提交');return}advanceAlert(a.id,action,action==='assign'?assignee.value:'运维值班员',note.value|| (action==='diagnose'?'已核实模拟阈值、点位与关联设备':action==='close'?'已复核遥测与处理记录，完成演示闭环':''));note.value=''}
function register(){if(addVisitor(visitor.value)){notify('访客登记成功，已授权到指定楼栋');visitor.value={name:'',company:'',buildingId:'A'}}else notify('请填写访客姓名与授权楼栋')}
function checkOut(v){v.status='已离院';v.outside=false;persist();notify('访客已签退')}
function optimize(){const targets=rooms.filter(r=>(!state.buildingId||r.buildingId===state.buildingId)&&(!state.floor||r.floor===state.floor)&&(!state.roomId||r.id===state.roomId)&&r.occupants===0);for(const r of targets)controlRoom(r.id,{light:false,hvac:false});efficiencyApplied.value=true;notify(`已对 ${targets.length} 个无人房间应用节能模拟控制`)}
function focusTrap(e){if(e.key!=='Tab')return;const nodes=dialog.value?.querySelectorAll('button:not([disabled]),input,select,textarea,[tabindex="0"]');if(!nodes?.length)return;const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}
onMounted(async()=>{priorFocus=document.activeElement;await nextTick();dialog.value?.querySelector('button')?.focus();document.addEventListener('keydown',focusTrap)})
onBeforeUnmount(()=>{document.removeEventListener('keydown',focusTrap);priorFocus?.focus?.()})
</script>

<template>
  <div class="modal-backdrop" @click.self="modal=null"><section ref="dialog" :class="['business-dialog',modal]" role="dialog" aria-modal="true" aria-labelledby="dialog-title"><header class="dialog-header"><div><h2 id="dialog-title">{{titles[modal]}}</h2><p>{{building?.name||'未来院区'}}<span v-if="room"> / {{room.number}} 室</span><span>所有遥测与事件均为模拟数据</span></p></div><button class="icon-button" aria-label="关闭弹窗" @click="modal=null"><X :size="21"/></button></header>

  <div v-if="modal==='alerts'" class="alert-workbench"><div class="alert-list"><div class="segmented"><button :class="{active:tab==='active'}" @click="tab='active'">待闭环</button><button :class="{active:tab==='closed'}" @click="tab='closed'">已闭环</button><button :class="{active:tab==='all'}" @click="tab='all'">全部</button></div><button v-for="a in alerts" :key="a.id" :class="['workbench-item',{active:selected?.id===a.id}]" @click="selectedAlertId=a.id;note=''"><span :class="['level-label',a.level]">{{a.level==='critical'?'重要':'一般'}}</span><strong>{{a.title}}</strong><p>{{getBuilding(getRoom(a.roomId).buildingId).name}} / {{a.roomId}}</p><small>{{a.id}}<span>{{statuses[a.status]}}</span></small></button><div v-if="!alerts.length" class="empty-state">当前分类暂无告警</div></div><div v-if="selected" class="alert-workspace"><div class="detail-title"><div><span class="eyebrow">{{selected.id}} · {{selected.system}}</span><h3>{{selected.title}}</h3></div><button class="quiet-button" @click="locateAlert(selected);modal=null"><Crosshair :size="15"/>三维定位</button></div><div class="workflow-steps"><div v-for="(s,i) in ['new','diagnosed','assigned','resolved','closed']" :key="s" :class="{done:['new','diagnosed','assigned','resolved','closed'].indexOf(selected.status)>=i}"><span>{{i+1}}</span><small>{{['发现','诊断','派单','处理','复盘'][i]}}</small></div></div><div class="diagnosis"><h4>事件诊断</h4><p>{{selected.detail}}</p><dl><div><dt>关联空间</dt><dd>{{getBuilding(getRoom(selected.roomId).buildingId).name}} · {{getRoom(selected.roomId).floor}}F · {{getRoom(selected.roomId).number}} 室</dd></div><div><dt>关联设备</dt><dd>{{selected.deviceId}}</dd></div><div><dt>触发时间</dt><dd>{{new Date(selected.createdAt).toLocaleString('zh-CN')}}</dd></div><div v-if="selected.assignee"><dt>工单处理人</dt><dd>{{selected.assignee}}</dd></div></dl><button class="text-link" @click="cameraId=getRoom(selected.roomId).buildingId;modal='video'">查看关联楼栋模拟监控<ArrowUpRight :size="13"/></button></div><div v-if="selected.status!=='closed'" class="process-form"><label v-if="selected.status==='diagnosed'">指派处理人<select v-model="assignee"><option>张工</option><option>李工</option><option>王工</option></select></label><label>处置记录{{selected.status==='assigned'?'（必填）':''}}<textarea v-model="note" rows="3" placeholder="记录诊断结果、处理措施或复核意见…"></textarea></label><button class="primary-button" @click="process"><ClipboardCheck :size="16"/>{{actions[nextAction[selected.status]]}}</button></div><div v-else class="closed-banner"><ShieldCheck :size="19"/>事件已闭环，完整处置记录已保留</div><div class="audit-log"><h4>处理时间线</h4><div v-for="(h,i) in selected.history" :key="i"><i></i><p><strong>{{actions[h.action]}}</strong><span>{{h.actor}} · {{new Date(h.at).toLocaleString('zh-CN')}}</span></p><small>{{h.note||'工单已指派'}}</small></div><p v-if="!selected.history.length" class="muted">等待值班员开始诊断</p></div></div></div>

  <div v-else-if="modal==='assets'" class="dialog-body"><div v-if="room" class="physical-summary"><div><span>空间面积</span><strong>{{room.area}} m²</strong></div><div><span>长 × 宽 × 高</span><strong>{{room.width.toFixed(2)}} × {{room.depth.toFixed(2)}} × {{room.height}} m</strong></div><div><span>三维局部坐标 X / Y / Z</span><strong>{{room.x.toFixed(2)}} / {{room.y.toFixed(2)}} / {{room.z.toFixed(2)}}</strong></div><div><span>空间 ID</span><strong>{{room.id}}</strong></div></div><div class="table-toolbar"><label class="search-box"><Search :size="16"/><input v-model="search" @input="assetPage=1" placeholder="搜索设备名称 / 编号" aria-label="搜索设备"/></label><select v-model="system" aria-label="筛选设备系统" @change="assetPage=1"><option v-for="s in ['全部','安防','消防','能源','楼控']" :key="s">{{s}}</option></select><span class="muted">共 {{assetList.length}} 台设备</span></div><div class="table-scroll"><table><thead><tr><th>设备 / 编号</th><th>系统</th><th>空间</th><th>状态</th><th>当前模拟读数</th><th>下次维护</th><th>操作</th></tr></thead><tbody><tr v-for="d in pageAssets" :key="d.id"><td><strong>{{d.label}}</strong><small>{{d.id}}</small></td><td>{{d.system}}</td><td>{{d.roomId||'室外公共空间'}}</td><td><span :class="['state-pill',d.online?'green':'orange']">{{d.online?'在线':'离线'}}</span></td><td>{{deviceReading(d,tick,state.controls,state.alerts)}}</td><td>{{d.maintenanceAt||'2026-10-15'}}</td><td><button class="text-link" @click="d.roomId?(selectRoom(d.roomId),modal=null):(state.showDevices=true,modal=null,notify('室外设施点位已在院区场景显示'))">定位<Crosshair :size="13"/></button></td></tr></tbody></table><div v-if="!assetList.length" class="empty-state">没有符合条件的设备</div></div><div class="pagination"><button :disabled="assetPage<=1" @click="assetPage--">上一页</button><span>{{Math.min(assetPage,Math.max(1,Math.ceil(assetList.length/pageSize)))}} / {{Math.max(1,Math.ceil(assetList.length/pageSize))}}</span><button :disabled="assetPage>=Math.ceil(assetList.length/pageSize)" @click="assetPage++">下一页</button></div></div>

  <div v-else-if="modal==='visitors'" class="dialog-body"><form class="visitor-form" @submit.prevent="register"><label>访客姓名<input v-model="visitor.name" maxlength="30" required placeholder="请输入姓名"/></label><label>来访单位<input v-model="visitor.company" maxlength="60" placeholder="可选"/></label><label>授权楼栋<select v-model="visitor.buildingId"><option v-for="b in buildings" :key="b.id" :value="b.id">{{b.name}}</option></select></label><button type="submit" class="primary-button"><Plus :size="15"/>登记访客</button></form><div class="info-banner"><ShieldCheck :size="18"/>电子围栏演示：每位访客仅授权进入指定楼栋，点击“模拟越界”可验证围栏告警。</div><div class="table-scroll"><table><thead><tr><th>访客 / 单位</th><th>授权区域</th><th>进入时间</th><th>状态</th><th>围栏演示</th></tr></thead><tbody><tr v-for="v in state.visitors" :key="v.id"><td><strong>{{v.name}}</strong><small>{{v.company||'个人来访'}}</small></td><td>{{getBuilding(v.buildingId).name}}</td><td>{{v.at}}</td><td><span :class="['state-pill',v.outside?'orange':'green']">{{v.outside?'越界预警':v.status}}</span></td><td><div class="table-actions"><button :disabled="v.status==='已离院'" @click="toggleVisitor(v.id)">{{v.outside?'返回授权区':'模拟越界'}}</button><button :disabled="v.status==='已离院'" @click="checkOut(v)">签退</button></div></td></tr></tbody></table></div><div v-if="state.visitors.some(v=>v.outside)" class="fence-warning"><Flame :size="18"/>围栏事件：{{state.visitors.filter(v=>v.outside).map(v=>v.name).join('、')}} 已偏离授权区域，请核查门禁记录。</div></div>

  <div v-else-if="modal==='video'" class="dialog-body video-dialog"><div class="camera-select"><button v-for="b in buildings" :key="b.id" :class="{active:cameraId===b.id}" @click="cameraId=b.id"><Video :size="15"/>{{b.name}}</button></div><div class="large-camera"><div class="camera-preview"><div class="camera-scene"><div class="camera-backwall"></div><div class="camera-door"></div><div class="camera-window"></div><div class="camera-floor"></div><div class="camera-desk"></div><div class="camera-desk second"></div></div><span class="camera-tag"><i></i>模拟画面 · 非真实监控</span><span class="camera-name">{{getBuilding(cameraId)?.name}} · {{cameraId==='E'?'后厨操作间':'大堂公共区域'}}</span><span class="camera-timestamp">CAM-{{cameraId}} / {{new Date().toLocaleTimeString('zh-CN')}}</span></div><div class="camera-metrics"><span><span class="live-dot"></span>演示通道在线</span><span>模拟人流 {{8+tick%4}} 人</span><span>真实视频接入：WebRTC / HLS 网关</span></div><div v-if="cameraId==='E'" class="kitchen-stats"><div><strong>4.2°C</strong><span>冷藏温度 · 正常</span></div><div><strong>0 ppm</strong><span>燃气泄漏 · 正常</span></div><div><strong>96%</strong><span>油烟净化效率 · 模拟</span></div></div><button class="wide-action" @click="selectRoom(`${cameraId}-${cameraId==='E'?'102':'101'}`);modal=null">定位关联空间<Crosshair :size="14"/></button></div></div>

  <div v-else-if="modal==='energy'" class="dialog-body"><div class="energy-dialog-top"><div><span class="muted">24 小时用量合计 · 模拟日曲线</span><h3>{{energyTotal.toFixed(1)}}<small>{{energyKind==='water'?'m³':'kWh'}}</small></h3></div><div class="segmented"><button :class="{active:energyKind==='electricity'}" @click="energyKind='electricity'">用电</button><button :class="{active:energyKind==='water'}" @click="energyKind='water'">用水</button></div></div><div class="large-chart"><TrendChart :data="series" id="energy-modal" :height="100" :color="energyKind==='water'?'#6eb9ef':'#48cab2'"/><div class="chart-axis"><span>00:00</span><span>06:00</span><span>12:00</span><span>18:00</span><span>23:00</span></div></div><div class="forecast-strip"><span>天气预测 · 模拟</span><span v-for="w in weatherForecast" :key="w.time">{{w.time}} <strong>{{w.temperature}}°C</strong></span></div><div class="energy-analysis"><section><h4>楼栋实时负荷排行</h4><div v-for="b in rank" :key="b.id" class="rank-row"><span>{{b.name}}</span><div><i :style="{width:b.power/rank[0].power*100+'%'}"></i></div><strong>{{b.power.toFixed(1)}} kW</strong></div></section><section class="optimization"><span class="small-chip green">节能建议</span><h4>让无人空间按需运行</h4><p>识别当前范围内无人房间，关闭模拟照明和空调。操作会更新房间控制与实时负荷，并保存在本地。</p><button class="primary-button" @click="optimize"><Lightbulb :size="15"/>{{efficiencyApplied?'再次应用模拟策略':'应用模拟节能策略'}}</button><small>历史日曲线不随当前控制追溯改写；真实冷热源效率、天气预测需接入外部数据服务。</small></section></div></div>

  <div v-else class="dialog-body help-content"><h3>从院区到每一个房间</h3><ol><li><strong>院区总览</strong>：拖动三维场景旋转，滚轮缩放；点击建筑或左侧空间树进入楼栋。</li><li><strong>楼层管理</strong>：楼栋默认展开楼层；点击楼层进入剖切视图，查看 8 间房间、走廊与家具。</li><li><strong>房间管理</strong>：点击房间查看物理尺寸、人员、传感器与设备；开关照明、空调可改变模拟功率。</li><li><strong>事件闭环</strong>：告警定位到具体房间，经诊断、派单、处理、复核后闭环。处理结果必须填写说明。</li><li><strong>人员与疏散</strong>：安防专题可登记访客并模拟电子围栏越界；疏散推演支持备用楼梯路径和容量估算。</li><li><strong>Blender 模型</strong>：使用项目 blender/generate_campus.py 脚本生成 .blend 与 .glb；从场景底部导入 GLB，可复用楼栋 ID 绑定。</li></ol><div class="info-banner">这是无需后端即可运行的完整交互演示。空间几何、遥测、视频示意、人员、天气与事件均为模拟；不连接实际设备。</div><h4>数据与接入边界</h4><p>房间控制、工单、访客存储在本机浏览器。生产部署需接入后端权限、审计、时序数据库、设备协议及视频网关；请参阅项目 README 和 docs/接入与数据规范.md。</p><p>场景使用米制本地坐标，不含真实地理测绘。管网以地表透视方式示意；应急路径采用简化通行模型，不替代消防设计及现场指挥。</p></div>
  </section></div>
</template>


