<script setup>
import { computed, ref, watch, nextTick } from 'vue'
import { Activity, ArrowUpRight, Bell, Building2, Check, ChevronRight, ClipboardList, Crosshair, DoorOpen, Droplets, Flame, Lightbulb, MapPin, Play, Route, ShieldCheck, Thermometer, Users, Video, Wind, Zap } from 'lucide-vue-next'
import { useTwin } from '../composables/useTwin.js'
import { buildings, rooms, devices, getRoom, getBuilding, telemetry, evacuation, hvacTelemetry } from '../data/campus.js'
const { state,tick,room,building,modal,openAlerts,selectedAlertId,locateAlert,selectRoom,controlRoom,notify,metrics }=useTwin()
const data=computed(()=>room.value?telemetry(room.value,tick.value,state.controls[room.value.id]):null)
const hvac=computed(()=>room.value?hvacTelemetry(room.value,tick.value,state.controls[room.value.id]):null)
const activeAlert=computed(()=>state.alerts.find(a=>a.id===selectedAlertId.value&&a.status!=='closed'))
const plan=computed(()=>room.value?evacuation(room.value,state.blocked):null)
const currentTime=computed(()=>{void tick.value;return new Date().toLocaleTimeString('zh-CN',{hour12:false})})
const detailColumn=ref(null)
watch(()=>[state.roomId,state.module,state.buildingId],async()=>{await nextTick();detailColumn.value?.scrollTo({top:0})})
const moduleTitles={overview:'运行态势',security:'安防监测',building:'楼宇智控',energy:'能源诊断',kitchen:'后厨监管',facility:'设施运维'}
const statusNames={new:'待诊断',diagnosed:'待派单',assigned:'处理中',resolved:'待复核',closed:'已闭环'}
function startEvacuation(){if(!room.value)selectRoom('A-301');state.evacuation=!state.evacuation;state.showDevices=true;if(state.evacuation)notify('演示疏散路径已生成，可切换楼梯封堵场景')}
</script>

<template>
  <aside ref="detailColumn" class="detail-column">
    <section v-if="room" class="room-detail panel">
      <div class="panel-heading"><h2><DoorOpen :size="16"/>房间空间档案</h2><span class="small-chip green">{{room.id}}</span></div>
      <div class="room-title"><div><span>{{building.name}} / {{room.floor}}F</span><h3>{{room.number}}<small>{{room.use}}</small></h3></div><span :class="['state-pill',openAlerts.some(a=>a.roomId===room.id)?'orange':'green']">{{openAlerts.some(a=>a.roomId===room.id)?'有告警':'运行正常'}}</span></div>
      <div class="room-specs"><div><span>使用面积</span><strong>{{room.area}} m²</strong></div><div><span>空间净高</span><strong>{{room.height}} m</strong></div><div><span>当前人数</span><strong>{{room.occupants}} / {{room.capacity}} 人</strong></div><div><span>管理负责人</span><strong>{{building.manager}}</strong></div></div>
      <div class="room-live"><span><Thermometer :size="14"/>{{data.temperature}} °C</span><span><Droplets :size="14"/>{{data.humidity}} %</span><span><Zap :size="14"/>{{data.power}} kW</span></div>
      <div class="control-row"><span><Lightbulb :size="15"/>智能照明</span><button class="switch" :class="{on:data.light}" role="switch" :aria-checked="data.light" aria-label="房间智能照明" @click="controlRoom(room.id,{light:!data.light})"><i></i></button></div>
      <label class="setpoint">照明亮度<input type="range" min="10" max="100" step="10" :value="data.brightness" :disabled="!data.light" @input="controlRoom(room.id,{brightness:Number($event.target.value)})"/><strong>{{data.brightness}}%</strong></label>
      <div class="control-row"><span><Wind :size="15"/>VRV 空调</span><button class="switch" :class="{on:data.hvac}" role="switch" :aria-checked="data.hvac" aria-label="房间空调" @click="controlRoom(room.id,{hvac:!data.hvac})"><i></i></button></div>
      <label class="setpoint">设定温度<input type="range" min="16" max="30" :value="data.setpoint" @input="controlRoom(room.id,{setpoint:Number($event.target.value)})"/><strong>{{data.setpoint}}°C</strong></label>
      <button class="wide-action" @click="modal='assets'"><ClipboardList :size="14"/>查看房间设备与物理空间<ChevronRight :size="14"/></button>
    </section>
    <section v-else class="health-panel panel"><div class="panel-heading"><h2><Activity :size="16"/>{{moduleTitles[state.module]}}</h2><span class="small-chip green">实时</span></div><div class="health-content"><div class="health-ring"><svg viewBox="0 0 110 110"><circle cx="55" cy="55" r="46" fill="none" stroke="#263d48" stroke-width="6"/><circle cx="55" cy="55" r="46" fill="none" stroke="#59c7b1" stroke-width="6" stroke-dasharray="269 289" stroke-linecap="round" transform="rotate(-90 55 55)"/></svg><div><strong>92<small>分</small></strong><span>模拟健康指数</span></div></div><div class="health-summary"><h3>整体运行良好</h3><p><span class="live-dot"></span>空间设备持续感知</p><p><i class="small-warning"></i>{{openAlerts.length}} 项事件待闭环</p><button @click="modal='assets'">查看设备台账<ArrowUpRight :size="12"/></button></div></div><div class="system-status"><span><i></i>安防系统</span><span><i></i>楼宇自控</span><span><i></i>能源监测</span><span><i class="orange-dot"></i>消防系统</span></div></section>

    <section v-if="room&&(state.module==='building'||state.module==='energy')" class="topic-panel panel"><div class="panel-heading"><h2><Wind :size="15"/>暖通运行与诊断</h2><span :class="['small-chip',hvac.risk?'orange':'green']">{{hvac.risk?'建议巡检':'运行平稳'}}</span></div><div class="room-specs"><div><span>空调负荷</span><strong>{{hvac.load}} %</strong></div><div><span>冷热源效率 COP</span><strong>{{hvac.cop||'停机'}}</strong></div><div><span>风机转速</span><strong>{{hvac.fanRpm}} rpm</strong></div><div><span>供暖模拟负荷</span><strong>{{hvac.heatingKw}} kW</strong></div></div><div class="topic-content"><p>下一小时负荷预估 {{hvac.forecastLoad}}%（规则模拟）。{{hvac.risk?'当前负荷较高或 COP 低于 3，建议检查滤网与换热器。':'运行参数在演示阈值内。'}}</p></div></section>
    <section v-if="state.module==='energy'" class="topic-panel panel"><div class="panel-heading"><h2><Zap :size="15"/>能源诊断</h2></div><div class="topic-content"><span class="muted">当前空间模拟瞬时负荷</span><strong class="topic-number">{{metrics.power.toFixed(1)}} <small>kW</small></strong><p>负荷较高的空间建议按需调整照明与空调。点击具体房间可模拟控制并观察功率变化。</p><button class="wide-action" @click="modal='energy'">打开水电能耗分析<ChevronRight :size="14"/></button></div></section>
    <section v-if="state.module==='security'" class="topic-panel panel"><div class="panel-heading"><h2><ShieldCheck :size="15"/>人员与访客</h2><span class="small-chip">{{state.visitors.length}} 位访客</span></div><div class="topic-content"><p>访客授权到楼栋，模拟越界将触发围栏事件；人员分布按实际模拟房间人数展示。</p><button class="wide-action" @click="modal='visitors'">访客登记与电子围栏<ChevronRight :size="14"/></button></div></section>
    <section v-if="state.module==='facility'" class="topic-panel panel"><div class="panel-heading"><h2><ClipboardList :size="15"/>公共设施巡检</h2></div><div class="topic-content"><p>配电间、水泵房、空调机房统一关联物理空间。维护计划与设备状态可按系统筛选。</p><button class="wide-action" @click="modal='assets'">查看设备台账<ChevronRight :size="14"/></button></div></section>
    <section v-if="state.module==='building'&&!room" class="topic-panel panel"><div class="panel-heading"><h2><Building2 :size="15"/>空间联动控制</h2></div><div class="topic-content"><p>从左侧选择楼层、房间，即可查看温湿度、照明和 VRV 空调，并调整运行参数。</p><button class="wide-action" @click="selectRoom('A-301')">进入 301 办公空间<ChevronRight :size="14"/></button></div></section>

    <section class="alerts-panel panel"><div class="panel-heading"><h2><Bell :size="16"/>实时告警<span class="count-badge">{{openAlerts.length}}</span></h2><button @click="modal='alerts'">全部<ChevronRight :size="13"/></button></div><div v-if="!openAlerts.length" class="empty-state"><ShieldCheck :size="24"/>全部告警已闭环</div><div v-for="a in openAlerts.slice(0,3)" :key="a.id" :class="['alert-item',{focused:activeAlert?.id===a.id}]" @click="locateAlert(a)"><span :class="['alert-icon',a.level]"><component :is="a.system==='消防'?Flame:a.system==='安防'?ShieldCheck:Zap" :size="16"/></span><div><div class="alert-title"><strong>{{a.title}}</strong><span>{{statusNames[a.status]}}</span></div><p>{{getBuilding(getRoom(a.roomId).buildingId).name}} · {{getRoom(a.roomId).number}} 室</p><small>{{new Date(a.createdAt).toLocaleTimeString('zh-CN',{hour12:false})}} <span>模拟事件</span></small></div><button class="locate-alert" title="定位告警房间" aria-label="定位告警房间" @click.stop="locateAlert(a)"><Crosshair :size="15"/></button></div><button v-if="activeAlert" class="wide-action alert-process" @click="modal='alerts'">处置当前告警 · {{activeAlert.id}}<ChevronRight :size="14"/></button></section>

    <section class="camera-panel panel"><div class="panel-heading"><h2><Video :size="16"/>{{state.module==='kitchen'?'明厨亮灶':'视频巡检'}}</h2><button @click="modal='video'">查看<ChevronRight :size="13"/></button></div><button class="camera-preview" @click="modal='video'" aria-label="打开模拟视频巡检"><div class="camera-scene"><div class="camera-backwall"></div><div class="camera-door"></div><div class="camera-window"></div><div class="camera-floor"></div><div class="camera-desk"></div><div class="camera-desk second"></div></div><span class="camera-tag"><i></i>模拟画面</span><span class="camera-timestamp">{{currentTime}}</span><span class="play-circle"><Play :size="17" fill="currentColor"/></span><span class="camera-name">{{state.module==='kitchen'?'生活服务中心 · 后厨操作间':(building?.name||'行政办公楼')+' · 大堂'}}</span></button></section>
    <section class="emergency-panel panel"><div class="emergency-heading"><span class="emergency-icon"><Route :size="19"/></span><div><h3>应急疏散推演</h3><p>虚拟场景验证 · 路径与容量估算</p></div></div><button :class="['primary-button',{running:state.evacuation}]" @click="startEvacuation"><Play :size="14"/>{{state.evacuation?'退出当前推演':'开始模拟推演'}}<ChevronRight :size="14"/></button><div v-if="state.evacuation&&plan" class="evacuation-details"><label><input type="checkbox" v-model="state.blocked"/>模拟东侧楼梯封堵</label><p>{{plan.stair}} → {{plan.assembly}}</p><div><span>{{plan.distance}} m 路程</span><span>约 {{plan.seconds}} 秒</span></div><p>楼梯理论通行量 {{plan.capacity}} 人/分钟</p><small>简化模型估算，仅供演示，不作为应急指挥依据。</small></div></section>
  </aside>
</template>

